# Generated by Django 6.0 on 2025-12-10 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_seed_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
            },
        ),
        migrations.RemoveIndex(
            model_name="topic",
            name="events_topi_event_i_4bec57_idx",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_topics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criador",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="events.event",
                verbose_name="Evento",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["event", "is_deleted", "created_at"], name="events_topi_event_i_366812_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="topic",
            name="vote_count",
        ),
    ]
