# Generated by Django 6.0 on 2025-12-10 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_default_site"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConcreteBaseModel",
        ),
        migrations.DeleteModel(
            name="ConcreteSoftDeleteModel",
        ),
    ]
