name: Run Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db
      DJANGO_SETTINGS_MODULE: floripatalks.settings
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run migrations
        run: uv run python manage.py migrate
      - name: Run tests
        run: uv run pytest
