name: Run Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: floripatalks.settings
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Create virtual environment
        run: uv venv .venv
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run migrations
        run: uv run python manage.py migrate
      - name: Run tests
        run: uv run pytest
